api/urls.py
# api/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import PostViewSet, CommentViewSet #,CustomLogoutView, LoginAPIView, LogoutAPIView
#from .views import custom_logout

router = DefaultRouter()
router.register(r'posts', PostViewSet)
router.register(r'comments', CommentViewSet)

urlpatterns = [
    path('', include(router.urls)),
   # path('login/', LoginAPIView.as_view(), name='api-login'),
    #path('api-authlogout/',  CustomLogoutView.as_view(), name='api-logout'),
]

django_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("team.urls")),
    path("", include("shop.urls")),
    path("", include("accounts.urls")),
    path("", include("post.urls")),
    path("", include("legal.urls")),
    path('api/', include('api.urls')),  # api/posts/ and api/comments/
    #path('api-auth',include("rest_framework.urls")),
    #path('api-authlogout/', custom_logout, name='api-logout'),  
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

legal/urls.py
from django.urls import path
from .views import disclaimer_view, impressum_view

app_name = 'legal'

urlpatterns = [
    path('disclaimer/', disclaimer_view, name='disclaimer'),
    path('impressum/', impressum_view, name='impressum'), 
    ]

post/urls.py
# posts/urls.py
from django.urls import path
from .views import PostListView, PostDetailView, add_comment

urlpatterns = [
    path("blog/", PostListView.as_view(), name="post_list"),
    path("blog/<int:pk>/", PostDetailView.as_view(), name="post_detail"),
    path("blog/<int:pk>/comment/", add_comment, name="add_comment"),
]

team/urls.py
from django.urls import path
from .views import (
    HomePageView,
    AboutPageView,
    TeamPageView,
    PlayerPageView,
    TestPageView
)
from django.contrib.auth import views as auth_views

app_name = 'team'

urlpatterns = [
    path("", HomePageView.as_view(), name="home_page"),
    path("about/", AboutPageView.as_view(), name="about_page"),
    path("players/", TeamPageView.as_view(), name="players_page"),
    path("players/<int:player_id>/", PlayerPageView.as_view(), name="player_data"),
]


post/models.py
# posts/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User

class Post(models.Model):
    title = models.CharField(max_length=50)
    body = models.TextField()
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Comment by {self.author.username} on {self.post.title}'

post/forms.py
# posts/forms.py
from django import forms
from .models import Post, Comment

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = '__all__'
        exclude = ['author']  # Exclude author field from the form

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = '__all__'

post/views.py
from django.shortcuts import redirect, get_object_or_404
from django.contrib import messages  
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views.generic import TemplateView, DetailView
from django.contrib.auth.decorators import login_required
from rest_framework import viewsets
from .serializers import PostSerializer
from .models import Post
from .forms import PostForm, CommentForm
import logging

class PostListView(TemplateView):
    template_name = 'post_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['posts'] = Post.objects.all()
        context['post_form'] = PostForm()  # Include an instance of the post form in the context
        context['comment_form'] = CommentForm()  # Include an instance of the comment form in the context
        return context
    
    def post(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect('login')

        post_form = PostForm(request.POST)
        if post_form.is_valid():
            post = post_form.save(commit=False)
            post.author = request.user
            post.save()
            messages.success(request, 'Thank you for posting!')
            return redirect('post_list')
        else:
            context = self.get_context_data()
            context['post_form'] = post_form
            return self.render_to_response(context)


class PostDetailView(DetailView):
    model = Post
    template_name = 'post_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        post = self.get_object()
        context['comments'] = post.comments.all()  
        context['comment_form'] = CommentForm(initial={'post': post, 'author': self.request.user})
        return context

logger = logging.getLogger(__name__)
@login_required
def add_comment(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == 'POST':
        comment_form = CommentForm(request.POST)
        print("POST data:", request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.post = post
            comment.author = request.user  # Set the author field to the logged-in user
            comment.save()
            return HttpResponseRedirect(reverse('post_detail', args=[pk]))
        else:
            # Log form errors for debugging
            logger.error(f"Invalid comment form submitted: {comment_form.errors}")
            messages.error(request, 'Error submitting comment form')
            # Redirect back to post detail page with error message
            return HttpResponseRedirect(reverse('post_detail', args=[pk]) + '?error=true')
    else:
        # Inform user to log in to perform the action
        messages.info(request, 'You need to log in to add a comment.')
        # Redirect to the login page
        return HttpResponseRedirect(reverse('login'))

# class PostViewSet(viewsets.ModelViewSet):
#     queryset = Post.objects.all()
#     serializer_class = PostSerializer

post/templates/base_post.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <title>CSS Template</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'style.css' %}">    
</head>

<body>
    <header>
        <div class="header-content">
            <h2>Python FC</h2>
            {% if user.is_authenticated %}
            <p class="logged-in-message">You are logged in as {{ user.username }}</p>
            <a href="{% url 'profile' %}" class="header-link">Your Profile</a>
            <a href="{% url 'logout' %}" class="header-link">Logout</a>
            {% else %}
            <a href="{% url 'login' %}" class="header-link">Login</a>
            <a href="{% url 'signup' %}" class="header-link">Signup</a>
            {% endif %}
        </div>
    </header>
    </header>

    <section>
        <nav>
            <ul>
                <li><a href="{% url 'team:home_page' %}"> Home</a></li>
                <li><a href="{% url 'team:about_page' %}"> About</a></li>
                <li><a href="{% url 'team:players_page' %}"> Players</a></li>
                <li><a href="{% url 'shop_home_page' %}"> Shop</a></li>
                <li><a href="{% url 'post_list' %}"> Blog</a></li>

          

            </ul>
        </nav>

        <div class="wrapper">
            <article class="article">
            {% block content %} {% endblock content %}

            {% block messages %}
                {% if messages %}
                    <ul class="messages">
                        {% for message in messages %}
                            <li>{{ message }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}
            {% endblock %}
        </article>
    </section>

    <footer>
        <p>Copyright 2024 Natalie Dutz <a href="{% url 'legal:disclaimer' %}">Disclaimer</a> <a href="{% url 'legal:impressum' %}">Impressum</a> </p>
    </footer>

</body>

</html>

post/templates/post_detail.html
{% extends 'base_post.html' %}

{% block content %}
  <!-- Post Details -->
  <div class="post-container">
    <h2>{{ post.title }}</h2>
    <p><strong>Author:</strong> {{ post.author }}</p>
    <p><strong>Date: </strong>{{ post.created_at|date:"M. d, Y, H:i" }}</p>
    <div class="post-body">
      {{ post.body }}
    </div>
  </div>

  <!-- Comments -->
  <h3>Comments</h3>
  <ul>
    {% for comment in comments %}
      <li>
        <div class="comment-container">
          <p>{{ comment.author }} says:</p>
          <div class="comment-text">
            {{ comment.text }}
          </div>
          <p>Date: {{ comment.created_at|date:"M. d, Y, H:i" }}</p>
        </div>
      </li>
    {% empty %}
      <li>No comments yet.</li>
    {% endfor %}
  </ul>

  <!-- Comment Form -->
  <form method="post" action="{% url 'add_comment' pk=post.pk %}">
    {% csrf_token %}
    <input type="hidden" name="author" value="{{ request.user.id }}"> <!-- Include a hidden input field to set the author -->
    <input type="hidden" name="post" value="{{ post.pk }}"> <!-- Include a hidden input field to set the post ID -->
    <div class="form-group">
        <label for="id_text">Your comment:</label>
        <br>
        {{ comment_form.text }}
    </div>
    <div class="form-group">
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
  </form>



{% endblock %}

post/templates/post_list.html
{% extends 'base_post.html' %}

{% block content %}
  <h1>To post, please fill out the form below:</h1>

  <!-- Post Form -->

  <form method="post" action="{% url 'post_list' %}">
    {% csrf_token %}
    <input type="hidden" name="author" value="{{ request.user.id }}"> <!-- Hidden input field for author -->
    <div class="form-group">
        <label for="title">Title:</label><br>
        <input class="form-control" type="text" id="title" name="title" placeholder="Your post title"><br> <!-- Add form-control class for styling -->
    </div>
    <div class="form-group">
        <label for="body">Body:</label><br>
        <textarea class="form-control" id="body" name="body" rows="10" cols="50" placeholder="Your post"></textarea><br> <!-- Increase rows and cols to make the textarea bigger -->
    </div>
    <button type="submit" class="btn btn-primary">Submit</button> <!-- Add btn and btn-primary classes for styling -->
  </form>

   <!-- Existing Posts -->
   <h1>Latest Posts</h1>
   <ul class="post-list">
     {% for post in posts %}
       <li class="post-item">
         <div class="post-header">
           <strong>Title:</strong> <a href="{% url 'post_detail' post.pk %}" class="post-link">{{ post.title }}</a><br>
           <strong>Author:</strong> {{ post.author }}<br>
           <strong>Date:</strong> {{ post.created_at|date:"M. d, Y, H:i" }}<br>
         </div>
         <div class="post-body">
           <strong>Excerpt:</strong> {{ post.body|truncatewords:20 }}
         </div>
       </li>
     {% endfor %}
   </ul>
 {% endblock %}