api/urls.py
# api/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import PostViewSet, CommentViewSet #,CustomLogoutView, LoginAPIView, LogoutAPIView
#from .views import custom_logout

router = DefaultRouter()
router.register(r'posts', PostViewSet)
router.register(r'comments', CommentViewSet)

urlpatterns = [
    path('', include(router.urls)),
   # path('login/', LoginAPIView.as_view(), name='api-login'),
    #path('api-authlogout/',  CustomLogoutView.as_view(), name='api-logout'),
]

django_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("team.urls")),
    path("", include("shop.urls")),
    path("", include("accounts.urls")),
    path("", include("post.urls")),
    path("", include("legal.urls")),
    path('api/', include('api.urls')),  # api/posts/ and api/comments/
    #path('api-auth',include("rest_framework.urls")),
    #path('api-authlogout/', custom_logout, name='api-logout'),  
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

legal/urls.py
from django.urls import path
from .views import disclaimer_view, impressum_view

app_name = 'legal'

urlpatterns = [
    path('disclaimer/', disclaimer_view, name='disclaimer'),
    path('impressum/', impressum_view, name='impressum'), 
    ]

shop/urls.py
from django.urls import path
from .views import ShopHomePageView, ProductListPageView, DetailedProductPageView, order_success_view

urlpatterns = [
    path("shop/", ShopHomePageView.as_view(), name="shop_home_page"),
    path("products/", ProductListPageView.as_view(), name="product_list_page"),
    path("products/<int:product_id>/", DetailedProductPageView.as_view(), name="detailed_product_page"),
    path('order-success/', order_success_view, name='order_success'),
    ]

team/urls.py
from django.urls import path
from .views import (
    HomePageView,
    AboutPageView,
    TeamPageView,
    PlayerPageView,
    TestPageView
)
from django.contrib.auth import views as auth_views

app_name = 'team'

urlpatterns = [
    path("", HomePageView.as_view(), name="home_page"),
    path("about/", AboutPageView.as_view(), name="about_page"),
    path("players/", TeamPageView.as_view(), name="players_page"),
    path("players/<int:player_id>/", PlayerPageView.as_view(), name="player_data"),
]


shop/models.py
from django.contrib.auth.models import User
from django.db import models
from accounts.models import Profile

class Item(models.Model):

    name = models.CharField(max_length=255)
    color = models.CharField(max_length=50, default="Unknown")  
    price = models.DecimalField(max_digits=10, decimal_places=2, default=0.0)  
    size = models.CharField(max_length=20, default="Unknown")
    quantity = models.PositiveIntegerField(default=0)
    image = models.ImageField(upload_to='item_images/', null=True, blank=True) 

    def __str__(self):
        return self.name

    
class Order(models.Model):
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    order_date = models.DateTimeField(auto_now_add=True)

    def total_price(self):
        return self.quantity * self.item.price

shop/forms.py
from django import forms
from .models import Order

class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['item', 'quantity']

shop/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.views import View
from django.urls import reverse
from .models import Order, Item
from .forms import OrderForm
from accounts.models import Profile
from django.contrib.auth.models import User

class ShopHomePageView(View):
    def get(self, request):
        return render(request, 'shop.html')

class ProductListPageView(View):
    def get(self, request):
        products = Item.objects.all()  # Fetch all products from the database
        return render(request, 'product_list_page.html', {'products': products})

class DetailedProductPageView(View):
    def get(self, request, product_id):
        product = get_object_or_404(Item, pk=product_id)
        form = OrderForm(initial={'item': product})
        return render(request, 'detailed_product_page.html', {'product': product, 'form': form})
    
    def post(self, request, product_id):
        if not request.user.is_authenticated:
            return redirect('login') 
        
        print("Post request received")

        product = get_object_or_404(Item, pk=product_id)
        profile = request.user.profile

        # # Check if the user is logged in
        # if not request.user.is_authenticated:
        #     # If not logged in, display a message and redirect to the login page
        #     messages.warning(request, 'Please log in to be able to make an order.')
        #     return redirect('login')

        if request.method == 'POST':
            print("POST method detected")

            form = OrderForm(request.POST)
            if form.is_valid():
                print("Form is valid")
                order = form.save(commit=False)
                order.item = product
                order.profile = profile 
                order.save()
                print("Order saved successfully")

            # Update item quantity or delete item
            quantity = form.cleaned_data.get('quantity', 1)
            product.quantity -= quantity
            if product.quantity <= 0:
                try:
                    product.delete()
                except Exception as e:
                    print(f"Error deleting product: {e}")

            else:
                product.save()

            # Redirect to order success view
            return redirect('order_success') 
        else:
            form = OrderForm(initial={'item': product}) 
        # Form is not valid, re-render the page with the form and product
            return render(request, 'detailed_product_page.html', {'product': product, 'form': form})
        
@login_required
def order_success_view(request):
    return render(request, 'order_success.html')

# @login_required
# def place_order(request):
#     if request.method == 'POST':
#         form = OrderForm(request.POST)
#         if form.is_valid():
#             order = form.save(commit=False)
#             order.user = request.user
#             order.save()

#             # Update item quantity or delete item
#             item_id = request.POST.get('product_id')
#             quantity = int(request.POST.get('quantity', 1))
#             item = get_object_or_404(Item, pk=item_id)
#             item.quantity -= quantity
#             if item.quantity <= 0:
#                 item.delete()
#             else:
#                 item.save()

#             # Render order success template
#             return render(request, 'order_success.html')
#     else:
#         form = OrderForm()
#     return render(request, 'detailed_product_page.html', {'form': form})

shop/templates/base_shop.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>CSS Template</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>

<body>
    <header>
        <div class="header-content">
            <h2>Python FC</h2>
            {% if user.is_authenticated %}
            <p class="logged-in-message">You are logged in as {{ user.username }}</p>
            <a href="{% url 'profile' %}" class="header-link">Your Profile</a>
            <a href="{% url 'logout' %}" class="header-link">Logout</a>
            {% else %}
            <a href="{% url 'login' %}" class="header-link">Login</a>
            <a href="{% url 'signup' %}" class="header-link">Signup</a>
            {% endif %}
        </div>
    </header>

    <div class="container">
        <nav>
            <ul>
                <li><a href="{% url 'team:home_page' %}"> Home</a></li>
                <li><a href="{% url 'team:about_page' %}"> About</a></li>
                <li><a href="{% url 'team:players_page' %}"> Players</a></li>
                <li><a href="{% url 'shop_home_page' %}"> Shop</a></li>
                <li><a href="{% url 'post_list' %}"> Blog</a></li>
            </ul>
        </nav>

        <div class="wrapper">
            <article class="article">
            {% block content %} {% endblock content %}
        </article>
    </div>

    <footer>
        <p>Copyright 2024 Natalie Dutz <a href="{% url 'legal:disclaimer' %}">Disclaimer</a> <a href="{% url 'legal:impressum' %}">Impressum</a> </p>
    </footer>
</body>
</html>

shop/templates/basepage_shop_app.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <title>CSS Template</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'style.css' %}">    
</head>

<body>

    <header>
        <h2>Shop Python FC</h2>
    </header>

    <section>
        <nav>
            <ul>
                <li><a href="{% url 'product_list_page' %}"> Product List</a></li>
                <li><a href="{% url 'home_page' %}"> Home</a></li>
          

            </ul>
        </nav>

        <article>
            {% block content %} {% endblock content %}
        </article>
    </section>

    <footer>
        <p>Footer</p>
    </footer>

</body>

</html>

shop/templates/detailed_product_page.html
{% extends "base_shop.html" %}

{% block content %}
    <h1>{{ product.name }}</h1>
    <img src="{{ product.image.url }}" alt="{{ product.name }}">
    <p>Color: {{ product.color }}</p>
    <p>Price: {{ product.price }}</p>
    <p>Size: {{ product.size }}</p>
    

    <form method="post" action="{% url 'detailed_product_page' product_id=product.id %}">
        {% csrf_token %}
        {{ form.as_p }} 
        <input type="submit" class="btn btn-primary" value="Order now" style="margin-top: 20px;">
    </form>
    
{% endblock %}

shop/templates/order_success.html
{% extends "base_shop.html" %}
{% block content %}
    <h1>Order Placed Successfully</h1>
    <p>Thank you for your order! Your order has been placed successfully.</p>
{% endblock %}

shop/templates/place_order.html
<!-- {% extends "base_shop.html" %}
<form method="post" action="{% url 'place_order' %}">
    {% csrf_token %}
    {{ form.non_field_errors }}
    <div class="form-group">
        {{ form.item.errors }}
        <label for="id_item">Product:</label>
        {{ form.item }}
    </div>
    <div class="form-group">
        {{ form.quantity.errors }}
        <label for="id_quantity">Quantity:</label>
        {{ form.quantity }}
    </div>
    <input type="submit" value="Place Order">
</form> -->

shop/templates/product_list_page.html
{% extends "base_shop.html" %}

{% block content %}
    <h1>Our Products</h1>
    <p>Please click on the product name below the image to see more info and to order.</p>
    <ul class="product-list">
        {% for product in products %}
            <li class="product-item">
                
                <div class="product-image">
                    <img src="{{ product.image.url }}" alt="{{ product.name }}" class="detail-image">
                </div>
                <div class="product-info">
                    <a href="{% url 'detailed_product_page' product.id %}" class="btn btn-primary">{{ product.name }} {{ product.size }}</a>
                </div>
            </li>
        {% endfor %}
    </ul>
{% endblock %}

shop/templates/shop.html
{% extends "base_shop.html" %}
{% block content %}
<title>Our Shop</title>
<body>
<div class="article"> 
<h2>Shop</h2>
<h3>You find all our products in the Product List.</h3>
<h3>Please click on the link below to see the list with all our products.</h3>

<ul style="list-style-type: none; padding: 0;">
    <li>
        <a href="{% url 'product_list_page' %}" class="btn btn-primary">Product List</a>
    </li>
</ul>
</div> 
</body> 
{% endblock content %}