api/urls.py
# api/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import PostViewSet, CommentViewSet #,CustomLogoutView, LoginAPIView, LogoutAPIView
#from .views import custom_logout

router = DefaultRouter()
router.register(r'posts', PostViewSet)
router.register(r'comments', CommentViewSet)

urlpatterns = [
    path('', include(router.urls)),
   # path('login/', LoginAPIView.as_view(), name='api-login'),
    #path('api-authlogout/',  CustomLogoutView.as_view(), name='api-logout'),
]

django_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("team.urls")),
    path("", include("shop.urls")),
    path("", include("accounts.urls")),
    path("", include("post.urls")),
    path("", include("legal.urls")),
    path('api/', include('api.urls')),  # api/posts/ and api/comments/
    #path('api-auth',include("rest_framework.urls")),
    #path('api-authlogout/', custom_logout, name='api-logout'),  
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

legal/urls.py
from django.urls import path
from .views import disclaimer_view, impressum_view

app_name = 'legal'

urlpatterns = [
    path('disclaimer/', disclaimer_view, name='disclaimer'),
    path('impressum/', impressum_view, name='impressum'), 
    ]

team/urls.py
from django.urls import path
from .views import (
    HomePageView,
    AboutPageView,
    TeamPageView,
    PlayerPageView,
    TestPageView
)
from django.contrib.auth import views as auth_views

app_name = 'team'

urlpatterns = [
    path("", HomePageView.as_view(), name="home_page"),
    path("about/", AboutPageView.as_view(), name="about_page"),
    path("players/", TeamPageView.as_view(), name="players_page"),
    path("players/<int:player_id>/", PlayerPageView.as_view(), name="player_data"),
]


team/models.py
from django.db import models



class Player(models.Model):
    """The Player model"""
    name = models.CharField(max_length=100, unique=True)
    age = models.PositiveIntegerField()
    position = models.CharField(max_length=100)

    
    def __str__(self):
        return self.name
    
    # class Meta:
    #     verbose_name = "Player"

class Game(models.Model):
    """The Game Model"""
    game_date = models.DateField(max_length=10, unique=True, default='1900-01-01')
    opponent = models.CharField(max_length=255)
    score = models.CharField(max_length=10)

    def __str__(self):
        return f"Game against {self.opponent}"


class GoalsScored(models.Model):
    """The Goals Scored Model"""
    game = models.ForeignKey(Game, on_delete=models.CASCADE, to_field='game_date')
    minute = models.PositiveBigIntegerField()
    player = models.ForeignKey(Player, on_delete=models.CASCADE, to_field='name', related_name='goals_scored')

    def __str__(self):
        return f"Goal made by {self.player.name} at {self.game.game_date}"


class Profile(models.Model):
    """The Profile Model"""
    player = models.OneToOneField(Player, on_delete=models.CASCADE, related_name='profile')
    height = models.FloatField()
    weight = models.FloatField()
    nationality = models.CharField(max_length=255)

    def __str__(self):
        return f"Profile of {self.player}"

class Team(models.Model):
    "The Team Model"
    team_name = models.CharField(max_length = 255)
    town = models.CharField(max_length = 255)
    color = models.CharField(max_length = 255)

    def __str__(self):
        return self.team_name

team/views.py
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseNotFound
from django.template.loader import get_template
from django.views.generic.base import TemplateView
from django.urls import reverse
from django.shortcuts import render
from .models import Player


class HomePageView(TemplateView):
    template_name = "home.html"


class AboutPageView(TemplateView):
    template_name = "about.html"


class TeamPageView(TemplateView):
    template_name = "team.html"

    def get_context_data(self):
        players = Player.objects.all()
        context = {"players": players}
        return context


class PlayerPageView(TemplateView):
    template_name = "player.html"

    def get_context_data(self, player_id):
        player = Player.objects.get(id=player_id)
        context = {"player": player}
        return context
    

class TestClass():

    textattr = "testattr"
    def __init__(self, text:str):
        self.text = text

    def get(self):
        return self.text.upper()
    
    @classmethod
    def getmethod(cls):
        return cls.textattr.upper()
    
class TestPageView(TemplateView):
    template_name = "test.html"

    def get_context_data(self):
        testobj = TestClass("instancestring")
        context = {"textlist": ["one", "two", "three"], 
                   "testobj": testobj, 
                   "emptylist": [],
                    "b": 100,
                    "names":"first, second, third",
                    "username": "george", 
                    "heading": "This is an example of 'escaping' with the characters > , > and &"}
        return context
























# from django.http import HttpResponse
# from django.urls import reverse
# from django.shortcuts import get_object_or_404
# from .models import Player
# from .data_import import players, goals_data



# def home_page_view(request):
#     url = reverse("about_page")
#     url1 = reverse("team_page")
#     url2 = reverse("player_page", args=[0])
#     url3 = reverse("scorers_page")

#     page = f"""
#     <!DOCTYPE html>
#     <html>
#     <head>
#     <title>Our Team</title>
#     </head>
#     <body>
#     <a href = "{url}">About Page</a>
#     <a href = "{url1}">Team Page</a>
#     <a href = "{url2}">Player Page</a>
#     <a href = "{url3}">Top Scorers Page</a>
#     <h1>This is the homepage of our Team</h1>
#     <p>This is the page with info about our team</p>
#     </body>
#     </html>
#     """
#     return HttpResponse(page)


# def about_page_view(request):
#     url = reverse("home_page")
#     url1 = reverse("team_page")
#     url2 = reverse("player_page", args=[0])
#     url3 = reverse("scorers_page")


#     page = f"""
#     <!DOCTYPE html>
#     <html>
#     <head>
#     <title>Our Team</title>
#     </head>
#     <body>
#     <a href = "{url}">Home Page</a>
#     <a href = "{url1}">Team Page</a>
#     <a href = "{url2}">Player Page</a>
#     <a href = "{url3}">Top Scorers Page</a>

#     <h1>About</h1>
#     <p>Here you can find information about our team.</p>
#     <h2>Contact data</h2>
#     <p>Address line 1</p>
#     <p>Address line 2</p>
#     <p>Address line 3</p>
#     </body>
#     </html>
#     """
#     return HttpResponse(page)


# def team_page_view(request):
#     url = reverse("home_page")
#     url1 = reverse("about_page")
#     url3 = reverse("player_page", args=[0])
#     url4 = reverse("scorers_page")
    
#     page_part1 = f"""
#     <!DOCTYPE html>
#     <html>
#     <head>
#     <title>Our Team</title>
#     </head>
#     <body>
#     <a href = "{url}">Home Page</a>
#     <a href = "{url1}">About Page</a>
#     <a href = "{url3}">Player Page</a>
#     <a href = "{url4}">Top Scorers Page</a>


#     <h1>Players of our Team</h1>
#     <p>This is the page with info about our team</p>
#     <ol>
#     """
#     index = 0
#     for player in players:
#         player_url = reverse("player_page", args=[index])
#         page_part1 += f'<li><a href ="{player_url}">' + player["name"] + "</a></li>"
#         index += 1

#     page_part2 = """
#     </ol>
#     </body>
#     </html>
#     """

#     return HttpResponse(page_part1 + page_part2)


# def player_page_view(request, player_id):
#     url = reverse("home_page")
#     url1 = reverse("about_page")
#     url2 = reverse("team_page")
#     url4 = reverse("scorers_page")

#     player = get_object_or_404(Player, id=player_id)

#     page = f"""
#     <!DOCTYPE html>
#     <html>
#     <head>
#     <title>Our Team</title>
#     </head>
#     <body>
#     <a href = "{url}">Home Page</a>
#      <a href = "{url1}">About Page</a>
#     <a href = "{url2}">Team Page</a>
#     <a href = "{url4}">Top Scorers Page</a>
#     <h1>About Player {player_id}</h1>
#     <p>Name: {players[player_id]["name"]}</p>
#     <p>Age: {players[player_id]["age"]}</p>
#     <p>Position: {players[player_id]["position"]}</p>
#     <h2>Profile:</h2>
#     <p>Height: {player.profile.height}</p>
#     <p>Weight: {player.profile.weight}</p>
#     <p>Nationality: {player.profile.nationality}</p>

#     </body>
#     </html>
#     """
#     return HttpResponse(page)

# def scorers_page_view(request):
#     url = reverse("home_page")
#     url1 = reverse("about_page")
#     url2 = reverse("team_page")
#     url3 = reverse("player_page", args=[0])


#     # Calculate the number of goals scored by each player
#     scorers = {}
#     for goal_data in goals_data:
#         player_name = goal_data["player_name"]
#         scorers[player_name] = scorers.get(player_name, 0) + 1

#     # Sort players by the number of goals scored
#     sorted_scorers = sorted(scorers.items(), key=lambda x: x[1], reverse=True)

#     page = f"""
#     <!DOCTYPE html>
#     <html>
#     <head>
#     <title>Our Scorers</title>
#     </head>
#     <body>
#     <a href = "{url}">Home Page</a>
#     <a href = "{url1}">About Page</a>
#     <a href = "{url2}">Team Page</a>
#     <a href = "{url3}">Player Page</a>
#     <h1>Top Scorers</h1>
#     <ol>
#     """

#     for player_name, goals_scored in sorted_scorers:
#         player_url = reverse("player_page", args=[players.index(next(p for p in players if p["name"] == player_name))])
#         page += f'<li><a href="{player_url}">{player_name}</a> - Goals: {goals_scored}</li>'

#     page += """
#     </ol>
#     </body>
#     </html>
#     """

#     return HttpResponse(page)

team/templates/about.html
{% extends "index.html" %}
{% load static %}

{% block content %}
<h1>Python FC About</h1>
<p>Here you find additional info about our team.</p>
<div>
    <p>Additional Information 1</p>
    <p>Additional Information 2</p>
    <p>Additional Information 3</p>
   
    </div>
    <img src="{% static 'playingsoccer.png' %}" alt="Python FC playing soccer">   
{% endblock content %}

team/templates/basepage_team_app.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <title>CSS Template</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>

<body>

    <header>
        <div class="header-content">
            <h2>Python FC</h2>
            {% if user.is_authenticated %}
            <a href="{% url 'logout' %}" class="header-link">Logout</a>
            {% else %}
            <a href="{% url 'login' %}" class="header-link">Login</a>
            <a href="{% url 'signup' %}" class="header-link">Signup</a>
            {% endif %}
        </div>
    </header>
    

    <section>
        <nav>
            <ul>
                <li><a href="{% url 'home_page' %}"> Home</a></li>
                <li><a href="{% url 'about_page' %}"> About</a></li>
                <li><a href="{% url 'players_page' %}"> Players</a></li>
                <li><a href="{% url 'shop_home_page' %}"> Shop</a></li>
            </ul>
        </nav>

        <article class="article">
            {% block content %} {% endblock content %}
        </article>
    </section>

    <footer>
        <p>Footer</p>
    </footer>

</body>

</html>

team/templates/home.html
{% extends "index.html" %}
{% load static %}

{% block content %}
<h1>Our Python FC Team</h1>
<p>This is the page with information about our team.</p>
<div>
<p>Information 1</p>
<p>Information 2</p>
<p>Information 3</p>
<img src="{% static 'soccerteam.png' %}" alt="Python FC">

</div>
{% endblock content %}

team/templates/index.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <title>CSS Template</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>

<body>

    <header>
        <div class="header-content">
            <h2>Python FC</h2>
            {% if user.is_authenticated %}
            <p class="logged-in-message">You are logged in as {{ user.username }}</p>
            <a href="{% url 'profile' %}" class="header-link">Your Profile</a>
            <a href="{% url 'logout' %}" class="header-link">Logout</a>
            {% else %}
            <a href="{% url 'login' %}" class="header-link">Login</a>
            <a href="{% url 'signup' %}" class="header-link">Signup</a>
            {% endif %}
        </div>
    </header>
    

    <section>
        <nav>
            <ul>
                <li><a href="{% url 'team:home_page' %}"> Home</a></li>
                <li><a href="{% url 'team:about_page' %}"> About</a></li>
                <li><a href="{% url 'team:players_page' %}"> Players</a></li>
                <li><a href="{% url 'shop_home_page' %}"> Shop</a></li>
                <li><a href="{% url 'post_list' %}"> Blog</a></li>


            </ul>
        </nav>
    <div class="wrapper">
        <article class="article">
            {% block content %} {% endblock content %}   
        </article>
    </div>   
    </section>
    <footer>
        <p>Copyright 2024 Natalie Dutz <a href="{% url 'legal:disclaimer' %}">Disclaimer</a> <a href="{% url 'legal:impressum' %}">Impressum</a> </p>
    </footer>

</body>

</html>

team/templates/player.html
{% extends "index.html" %}

{% block content %}
<div class="player-container">
    <div class="player-info">
        <h1>About Player {{ player.name }}</h1>
        <p><strong>Name:</strong> {{ player.name }}</p>
        <p><strong>Age:</strong> {{ player.age }}</p>
        <p><strong>Position:</strong> {{ player.position }}</p>
        <p><strong>Height:</strong> {{ player.profile.height }}</p>
        <p><strong>Weight:</strong> {{ player.profile.weight }}</p>
        <p><strong>Nationality:</strong> {{ player.profile.nationality }}</p>
        
    </div>

    <div class="additional-info">
        <h2>Games Played</h2>
        {% if player.goals_scored.all %}
            <ul>
                {% for goal in player.goals_scored.all %}
                    <li>{{ goal.game.opponent }} - {{ goal.game.game_date }}</li>
                {% endfor %}
            </ul>

            <h2>Goals Scored</h2>
            <ul>
                {% for goal in player.goals_scored.all %}
                    <li>Goal scored against {{ goal.game.opponent }} at {{ goal.minute }}'</li>
                {% endfor %}
            </ul>
        {% else %}
            <p>No games played yet</p>
        {% endif %}
        
        {% if not player.goals_scored.all %}
            <h2>Goals Scored</h2>
            <p>No goals scored yet</p>
        {% endif %}
    </div>
</div>
{% endblock content %}

team/templates/team.html
{% extends "index.html" %}

{% block content %}
<h1>This is the roster of our Team.</h1>
<p>Please click on the name of a player to get more detailed information.</p>

<div class="player-list">
    {% for player in players %}
    <div class="player-list-item">
        <a href="{% url 'team:player_data' player.id %}">
            <h3>{{ player.name }}</h3>
        </a>
    </div>
    {% endfor %}
</div>
{% endblock content %}